version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - thinceller
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
  - dependency-name: nextra-theme-blog
    versions:
    - 0.1.4
  - dependency-name: nextra
    versions:
    - 0.4.0
    - 0.4.1
    - 0.4.2
    - 0.4.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
