name: reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review # Change reporter.
          fail_on_error: true
